// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cấu trúc map với model.Server
type Server struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerId          string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName        string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ipv4              string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MetadataUpdatedAt int64                  `protobuf:"varint,6,opt,name=metadata_updated_at,json=metadataUpdatedAt,proto3" json:"metadata_updated_at,omitempty"`
	LastPingAt        int64                  `protobuf:"varint,7,opt,name=last_ping_at,json=lastPingAt,proto3" json:"last_ping_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Server) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Server) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *Server) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Server) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Server) GetMetadataUpdatedAt() int64 {
	if x != nil {
		return x.MetadataUpdatedAt
	}
	return 0
}

func (x *Server) GetLastPingAt() int64 {
	if x != nil {
		return x.LastPingAt
	}
	return 0
}

type CreateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ipv4          string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *CreateServerRequest) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

type UpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Ipv4          string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServerRequest) Reset() {
	*x = UpdateServerRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServerRequest) ProtoMessage() {}

func (x *UpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServerRequest.ProtoReflect.Descriptor instead.
func (*UpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateServerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UpdateServerRequest) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

// Cấu trúc map với model.ListServerFilter
type ListServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	SortField     string                 `protobuf:"bytes,3,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	Desc          bool                   `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersRequest) Reset() {
	*x = ListServersRequest{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersRequest) ProtoMessage() {}

func (x *ListServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersRequest.ProtoReflect.Descriptor instead.
func (*ListServersRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *ListServersRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ListServersRequest) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ListServersRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *ListServersRequest) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// Cấu trúc map với model.ListServerResult
type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *ListServersResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ListServersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ImportServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportServersRequest) Reset() {
	*x = ImportServersRequest{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportServersRequest) ProtoMessage() {}

func (x *ImportServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportServersRequest.ProtoReflect.Descriptor instead.
func (*ImportServersRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *ImportServersRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

// Cấu trúc map với model.CreateBatchServerResult
type ImportServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessIds    []string               `protobuf:"bytes,1,rep,name=success_ids,json=successIds,proto3" json:"success_ids,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	SuccessCnt    int32                  `protobuf:"varint,3,opt,name=success_cnt,json=successCnt,proto3" json:"success_cnt,omitempty"`
	FailedCnt     int32                  `protobuf:"varint,4,opt,name=failed_cnt,json=failedCnt,proto3" json:"failed_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportServersResponse) Reset() {
	*x = ImportServersResponse{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportServersResponse) ProtoMessage() {}

func (x *ImportServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportServersResponse.ProtoReflect.Descriptor instead.
func (*ImportServersResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *ImportServersResponse) GetSuccessIds() []string {
	if x != nil {
		return x.SuccessIds
	}
	return nil
}

func (x *ImportServersResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *ImportServersResponse) GetSuccessCnt() int32 {
	if x != nil {
		return x.SuccessCnt
	}
	return 0
}

func (x *ImportServersResponse) GetFailedCnt() int32 {
	if x != nil {
		return x.FailedCnt
	}
	return 0
}

type ExportServersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	SortField     string                 `protobuf:"bytes,3,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	Desc          bool                   `protobuf:"varint,4,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportServersRequest) Reset() {
	*x = ExportServersRequest{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportServersRequest) ProtoMessage() {}

func (x *ExportServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportServersRequest.ProtoReflect.Descriptor instead.
func (*ExportServersRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *ExportServersRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *ExportServersRequest) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *ExportServersRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *ExportServersRequest) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

type ExportServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportServersResponse) Reset() {
	*x = ExportServersResponse{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportServersResponse) ProtoMessage() {}

func (x *ExportServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportServersResponse.ProtoReflect.Descriptor instead.
func (*ExportServersResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *ExportServersResponse) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ExportServersResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\"\xe3\x01\n" +
	"\x06Server\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12.\n" +
	"\x13metadata_updated_at\x18\x06 \x01(\x03R\x11metadataUpdatedAt\x12 \n" +
	"\flast_ping_at\x18\a \x01(\x03R\n" +
	"lastPingAt\"g\n" +
	"\x13CreateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\"g\n" +
	"\x13UpdateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\"2\n" +
	"\x13DeleteServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\x16\n" +
	"\x14DeleteServerResponse\"k\n" +
	"\x12ListServersRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\tR\tsortField\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\bR\x04desc\"U\n" +
	"\x13ListServersResponse\x12(\n" +
	"\aservers\x18\x01 \x03(\v2\x0e.server.ServerR\aservers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\x14ImportServersRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\"\x97\x01\n" +
	"\x15ImportServersResponse\x12\x1f\n" +
	"\vsuccess_ids\x18\x01 \x03(\tR\n" +
	"successIds\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\x12\x1f\n" +
	"\vsuccess_cnt\x18\x03 \x01(\x05R\n" +
	"successCnt\x12\x1d\n" +
	"\n" +
	"failed_cnt\x18\x04 \x01(\x05R\tfailedCnt\"m\n" +
	"\x14ExportServersRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\tR\tsortField\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\bR\x04desc\"W\n" +
	"\x15ExportServersResponse\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName2\xb8\x03\n" +
	"\rServerService\x12;\n" +
	"\fCreateServer\x12\x1b.server.CreateServerRequest\x1a\x0e.server.Server\x12;\n" +
	"\fUpdateServer\x12\x1b.server.UpdateServerRequest\x1a\x0e.server.Server\x12I\n" +
	"\fDeleteServer\x12\x1b.server.DeleteServerRequest\x1a\x1c.server.DeleteServerResponse\x12F\n" +
	"\vListServers\x12\x1a.server.ListServersRequest\x1a\x1b.server.ListServersResponse\x12L\n" +
	"\rImportServers\x12\x1c.server.ImportServersRequest\x1a\x1d.server.ImportServersResponse\x12L\n" +
	"\rExportServers\x12\x1c.server.ExportServersRequest\x1a\x1d.server.ExportServersResponseBCZAgithub.com/LeHuuHai/server-management/microservices/pkg/pb/serverb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_server_proto_goTypes = []any{
	(*Server)(nil),                // 0: server.Server
	(*CreateServerRequest)(nil),   // 1: server.CreateServerRequest
	(*UpdateServerRequest)(nil),   // 2: server.UpdateServerRequest
	(*DeleteServerRequest)(nil),   // 3: server.DeleteServerRequest
	(*DeleteServerResponse)(nil),  // 4: server.DeleteServerResponse
	(*ListServersRequest)(nil),    // 5: server.ListServersRequest
	(*ListServersResponse)(nil),   // 6: server.ListServersResponse
	(*ImportServersRequest)(nil),  // 7: server.ImportServersRequest
	(*ImportServersResponse)(nil), // 8: server.ImportServersResponse
	(*ExportServersRequest)(nil),  // 9: server.ExportServersRequest
	(*ExportServersResponse)(nil), // 10: server.ExportServersResponse
}
var file_server_proto_depIdxs = []int32{
	0,  // 0: server.ListServersResponse.servers:type_name -> server.Server
	1,  // 1: server.ServerService.CreateServer:input_type -> server.CreateServerRequest
	2,  // 2: server.ServerService.UpdateServer:input_type -> server.UpdateServerRequest
	3,  // 3: server.ServerService.DeleteServer:input_type -> server.DeleteServerRequest
	5,  // 4: server.ServerService.ListServers:input_type -> server.ListServersRequest
	7,  // 5: server.ServerService.ImportServers:input_type -> server.ImportServersRequest
	9,  // 6: server.ServerService.ExportServers:input_type -> server.ExportServersRequest
	0,  // 7: server.ServerService.CreateServer:output_type -> server.Server
	0,  // 8: server.ServerService.UpdateServer:output_type -> server.Server
	4,  // 9: server.ServerService.DeleteServer:output_type -> server.DeleteServerResponse
	6,  // 10: server.ServerService.ListServers:output_type -> server.ListServersResponse
	8,  // 11: server.ServerService.ImportServers:output_type -> server.ImportServersResponse
	10, // 12: server.ServerService.ExportServers:output_type -> server.ExportServersResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
