// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: monitor.proto

package monitorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalFileTransferService_DownloadReport_FullMethodName = "/monitor.InternalFileTransferService/DownloadReport"
)

// InternalFileTransferServiceClient is the client API for InternalFileTransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Dành cho Internal (Mail Worker gọi vào)
type InternalFileTransferServiceClient interface {
	DownloadReport(ctx context.Context, in *DownloadReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadReportResponse], error)
}

type internalFileTransferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalFileTransferServiceClient(cc grpc.ClientConnInterface) InternalFileTransferServiceClient {
	return &internalFileTransferServiceClient{cc}
}

func (c *internalFileTransferServiceClient) DownloadReport(ctx context.Context, in *DownloadReportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalFileTransferService_ServiceDesc.Streams[0], InternalFileTransferService_DownloadReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadReportRequest, DownloadReportResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalFileTransferService_DownloadReportClient = grpc.ServerStreamingClient[DownloadReportResponse]

// InternalFileTransferServiceServer is the server API for InternalFileTransferService service.
// All implementations must embed UnimplementedInternalFileTransferServiceServer
// for forward compatibility.
//
// Dành cho Internal (Mail Worker gọi vào)
type InternalFileTransferServiceServer interface {
	DownloadReport(*DownloadReportRequest, grpc.ServerStreamingServer[DownloadReportResponse]) error
	mustEmbedUnimplementedInternalFileTransferServiceServer()
}

// UnimplementedInternalFileTransferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalFileTransferServiceServer struct{}

func (UnimplementedInternalFileTransferServiceServer) DownloadReport(*DownloadReportRequest, grpc.ServerStreamingServer[DownloadReportResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadReport not implemented")
}
func (UnimplementedInternalFileTransferServiceServer) mustEmbedUnimplementedInternalFileTransferServiceServer() {
}
func (UnimplementedInternalFileTransferServiceServer) testEmbeddedByValue() {}

// UnsafeInternalFileTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalFileTransferServiceServer will
// result in compilation errors.
type UnsafeInternalFileTransferServiceServer interface {
	mustEmbedUnimplementedInternalFileTransferServiceServer()
}

func RegisterInternalFileTransferServiceServer(s grpc.ServiceRegistrar, srv InternalFileTransferServiceServer) {
	// If the following call panics, it indicates UnimplementedInternalFileTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalFileTransferService_ServiceDesc, srv)
}

func _InternalFileTransferService_DownloadReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadReportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalFileTransferServiceServer).DownloadReport(m, &grpc.GenericServerStream[DownloadReportRequest, DownloadReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalFileTransferService_DownloadReportServer = grpc.ServerStreamingServer[DownloadReportResponse]

// InternalFileTransferService_ServiceDesc is the grpc.ServiceDesc for InternalFileTransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalFileTransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.InternalFileTransferService",
	HandlerType: (*InternalFileTransferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadReport",
			Handler:       _InternalFileTransferService_DownloadReport_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitor.proto",
}
