// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// HeartbeatRequest defines model for HeartbeatRequest.
type HeartbeatRequest struct {
	ServerId string `json:"server_id"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// SendHeartbeatJSONRequestBody defines body for SendHeartbeat for application/json ContentType.
type SendHeartbeatJSONRequestBody = HeartbeatRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send server heartbeat
	// (POST /heartbeat)
	SendHeartbeat(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SendHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) SendHeartbeat(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendHeartbeat(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/heartbeat", wrapper.SendHeartbeat)
}

type BadRequestJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type SendHeartbeatRequestObject struct {
	Body *SendHeartbeatJSONRequestBody
}

type SendHeartbeatResponseObject interface {
	VisitSendHeartbeatResponse(w http.ResponseWriter) error
}

type SendHeartbeat202Response struct {
}

func (response SendHeartbeat202Response) VisitSendHeartbeatResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type SendHeartbeat400JSONResponse struct{ BadRequestJSONResponse }

func (response SendHeartbeat400JSONResponse) VisitSendHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendHeartbeat401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendHeartbeat401JSONResponse) VisitSendHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHeartbeat500JSONResponse struct{ InternalErrorJSONResponse }

func (response SendHeartbeat500JSONResponse) VisitSendHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Send server heartbeat
	// (POST /heartbeat)
	SendHeartbeat(ctx context.Context, request SendHeartbeatRequestObject) (SendHeartbeatResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// SendHeartbeat operation middleware
func (sh *strictHandler) SendHeartbeat(ctx *gin.Context) {
	var request SendHeartbeatRequestObject

	var body SendHeartbeatJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendHeartbeat(ctx, request.(SendHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendHeartbeat")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SendHeartbeatResponseObject); ok {
		if err := validResponse.VisitSendHeartbeatResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUT2vbThD9KmJ+v6NiKU4LQTcHSmtyMQmFgjFlI42tDdLudnaUopr97mVWtmzhhPZQ",
	"ctP+mfdm3nvaPZS2ddagYQ/FHgi9s8ZjXNyp6gF/dOhZVqU1jCZ+KucaXSrW1mTP3hrZ82WNrZKv/wm3",
	"UMB/2Qk6G0599onI0sOBBEIIKVToS9JOwKAQzoQOpCGFpWEko5pY935dHGkTj/SClGCkDyl8Narj2pL+",
	"hdX7tTNhleNDpQBPi4s9OLIOifXgYWmruMu9QyjAM2mzk0la9F7tXj87GPBdV68ch/S4Y5+esYw2fUFF",
	"/ISKz/Iy7WMQ8k1EYdQkmq7Prm4uqGR2LDvS3D+KBgO4cvoe+0XHtay0SFajqpAgBaNaAfh2tVgtr+6x",
	"hxFzqBr01mZrpXaq+2K1TLaWjimoj1Mm2uzQy6WZwGluBG8UIfmsGH+qPlmslpDCC5If8K5n+SwXvaxD",
	"o5yGAm5m+ewGUnCK6zhLNrJEEe0gpkgZo7WsoIBHNNXIBqNfd7bq/1koLywNU5+YOowbZw/GPJ9finiS",
	"RZUlOpYIp/Ahz9/qYITMzh6gWHL955Lpr5LCx7/hmb4y5yGDYj2N13oTNin4rm0V9QcrLvIhoVA7L2E+",
	"2bQJA7Bc9RG3o0aSyuyKLGtsqZraei5u89s5hE34HQAA//+2QZZfnAUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
