// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateServerRequest defines model for CreateServerRequest.
type CreateServerRequest struct {
	Ipv4       string `json:"ipv4"`
	ServerId   string `json:"server_id"`
	ServerName string `json:"server_name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// GetListServersResponse defines model for GetListServersResponse.
type GetListServersResponse struct {
	Items *[]Server `json:"items,omitempty"`
	Total *int      `json:"total,omitempty"`
}

// ImportServerResponse defines model for ImportServerResponse.
type ImportServerResponse struct {
	IdFailed     []string `json:"id_failed"`
	IdSuccess    []string `json:"id_success"`
	TotalFailed  int      `json:"total_failed"`
	TotalSuccess int      `json:"total_success"`
}

// Server defines model for Server.
type Server struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Ipv4       string     `json:"ipv4"`
	ServerId   string     `json:"server_id"`
	ServerName string     `json:"server_name"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// UpdateServerRequest defines model for UpdateServerRequest.
type UpdateServerRequest struct {
	Ipv4       *string `json:"ipv4,omitempty"`
	ServerName *string `json:"server_name,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetListServersParams defines parameters for GetListServers.
type GetListServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ExportServersParams defines parameters for ExportServers.
type ExportServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ImportServerMultipartBody defines parameters for ImportServer.
type ImportServerMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServerRequest

// ImportServerMultipartRequestBody defines body for ImportServer for multipart/form-data ContentType.
type ImportServerMultipartRequestBody ImportServerMultipartBody

// UpdateServerJSONRequestBody defines body for UpdateServer for application/json ContentType.
type UpdateServerJSONRequestBody = UpdateServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get list servers
	// (GET /servers)
	GetListServers(c *gin.Context, params GetListServersParams)
	// Create server
	// (POST /servers)
	CreateServer(c *gin.Context)
	// Export servers
	// (GET /servers/export)
	ExportServers(c *gin.Context, params ExportServersParams)
	// Import server
	// (POST /servers/import)
	ImportServer(c *gin.Context)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(c *gin.Context, serverId string)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(c *gin.Context, serverId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetListServers operation middleware
func (siw *ServerInterfaceWrapper) GetListServers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"server:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListServersParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	if paramValue := c.Query("sort_field"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument sort_field is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	if paramValue := c.Query("desc"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument desc is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "desc", c.Request.URL.Query(), &params.Desc)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListServers(c, params)
}

// CreateServer operation middleware
func (siw *ServerInterfaceWrapper) CreateServer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:create"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateServer(c)
}

// ExportServers operation middleware
func (siw *ServerInterfaceWrapper) ExportServers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"server:export"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportServersParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	if paramValue := c.Query("sort_field"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument sort_field is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	if paramValue := c.Query("desc"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument desc is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "desc", c.Request.URL.Query(), &params.Desc)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportServers(c, params)
}

// ImportServer operation middleware
func (siw *ServerInterfaceWrapper) ImportServer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:import"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportServer(c)
}

// DeleteServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteServer(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"server:delete"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteServer(c, serverId)
}

// UpdateServer operation middleware
func (siw *ServerInterfaceWrapper) UpdateServer(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"server:update"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateServer(c, serverId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/servers", wrapper.GetListServers)
	router.POST(options.BaseURL+"/servers", wrapper.CreateServer)
	router.GET(options.BaseURL+"/servers/export", wrapper.ExportServers)
	router.POST(options.BaseURL+"/servers/import", wrapper.ImportServer)
	router.DELETE(options.BaseURL+"/servers/:server_id", wrapper.DeleteServer)
	router.PATCH(options.BaseURL+"/servers/:server_id", wrapper.UpdateServer)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GetListServersRequestObject struct {
	Params GetListServersParams
}

type GetListServersResponseObject interface {
	VisitGetListServersResponse(w http.ResponseWriter) error
}

type GetListServers200JSONResponse GetListServersResponse

func (response GetListServers200JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers400JSONResponse struct{ BadRequestJSONResponse }

func (response GetListServers400JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetListServers401JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetListServers403JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetListServers500JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateServerRequestObject struct {
	Body *CreateServerJSONRequestBody
}

type CreateServerResponseObject interface {
	VisitCreateServerResponse(w http.ResponseWriter) error
}

type CreateServer201JSONResponse Server

func (response CreateServer201JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateServer400JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateServer401JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateServer403JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer409JSONResponse struct{ ConflictJSONResponse }

func (response CreateServer409JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateServer500JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportServersRequestObject struct {
	Params ExportServersParams
}

type ExportServersResponseObject interface {
	VisitExportServersResponse(w http.ResponseWriter) error
}

type ExportServers200ResponseHeaders struct {
	ContentDisposition string
}

type ExportServers200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse struct {
	Body          io.Reader
	Headers       ExportServers200ResponseHeaders
	ContentLength int64
}

func (response ExportServers200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ExportServers400JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportServers401JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ExportServers403JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportServers500JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportServerRequestObject struct {
	Body *multipart.Reader
}

type ImportServerResponseObject interface {
	VisitImportServerResponse(w http.ResponseWriter) error
}

type ImportServer200JSONResponse ImportServerResponse

func (response ImportServer200JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportServer400JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportServer401JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response ImportServer403JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportServer500JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServerRequestObject struct {
	ServerId string `json:"server_id"`
}

type DeleteServerResponseObject interface {
	VisitDeleteServerResponse(w http.ResponseWriter) error
}

type DeleteServer204Response struct {
}

func (response DeleteServer204Response) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteServer401JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteServer403JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteServer404JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteServer500JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServerRequestObject struct {
	ServerId string `json:"server_id"`
	Body     *UpdateServerJSONRequestBody
}

type UpdateServerResponseObject interface {
	VisitUpdateServerResponse(w http.ResponseWriter) error
}

type UpdateServer200JSONResponse Server

func (response UpdateServer200JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateServer400JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateServer401JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateServer403JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateServer404JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateServer500JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get list servers
	// (GET /servers)
	GetListServers(ctx context.Context, request GetListServersRequestObject) (GetListServersResponseObject, error)
	// Create server
	// (POST /servers)
	CreateServer(ctx context.Context, request CreateServerRequestObject) (CreateServerResponseObject, error)
	// Export servers
	// (GET /servers/export)
	ExportServers(ctx context.Context, request ExportServersRequestObject) (ExportServersResponseObject, error)
	// Import server
	// (POST /servers/import)
	ImportServer(ctx context.Context, request ImportServerRequestObject) (ImportServerResponseObject, error)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(ctx context.Context, request DeleteServerRequestObject) (DeleteServerResponseObject, error)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(ctx context.Context, request UpdateServerRequestObject) (UpdateServerResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetListServers operation middleware
func (sh *strictHandler) GetListServers(ctx *gin.Context, params GetListServersParams) {
	var request GetListServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetListServers(ctx, request.(GetListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetListServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetListServersResponseObject); ok {
		if err := validResponse.VisitGetListServersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServer operation middleware
func (sh *strictHandler) CreateServer(ctx *gin.Context) {
	var request CreateServerRequestObject

	var body CreateServerJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServer(ctx, request.(CreateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateServerResponseObject); ok {
		if err := validResponse.VisitCreateServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportServers operation middleware
func (sh *strictHandler) ExportServers(ctx *gin.Context, params ExportServersParams) {
	var request ExportServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExportServers(ctx, request.(ExportServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ExportServersResponseObject); ok {
		if err := validResponse.VisitExportServersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportServer operation middleware
func (sh *strictHandler) ImportServer(ctx *gin.Context) {
	var request ImportServerRequestObject

	if reader, err := ctx.Request.MultipartReader(); err == nil {
		request.Body = reader
	} else {
		ctx.Error(err)
		return
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportServer(ctx, request.(ImportServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ImportServerResponseObject); ok {
		if err := validResponse.VisitImportServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteServer operation middleware
func (sh *strictHandler) DeleteServer(ctx *gin.Context, serverId string) {
	var request DeleteServerRequestObject

	request.ServerId = serverId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteServer(ctx, request.(DeleteServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteServerResponseObject); ok {
		if err := validResponse.VisitDeleteServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateServer operation middleware
func (sh *strictHandler) UpdateServer(ctx *gin.Context, serverId string) {
	var request UpdateServerRequestObject

	request.ServerId = serverId

	var body UpdateServerJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateServer(ctx, request.(UpdateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateServerResponseObject); ok {
		if err := validResponse.VisitUpdateServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xY3W/bNhD/VwRuj4rtLBnQadhDmjZFhmEo0hZ7SIOAEU82C4pUyVNgz9D/PpCUbH3Q",
	"H0EdN8P2ZEviffDu97s7cklSlRdKgkRDkiXRYAolDbiH15TdwNcSDNqnVEkE6f7SohA8pciVHH8xStp3",
	"Jp1BTu2/HzVkJCE/jNeqx/6rGb/VWumb2gipqiomDEyqeWGVkcTajHRttIrJpZKZ4OkRHbgBo0qdQpQ2",
	"pquYXCn9wBkDeTw/1iarmFxLBC2pcFLH86ExGxnQj6AjcOarmPyp8EqVkn2HtEiFUeZsVzH5JGmJM6X5",
	"33BEXzpW7eda0iq+1EARPrh4tchTaFWARu6JxYvHc/ubKZ1TJIl/ERNcFEASYlBzObX783G/525zm75K",
	"mkPgexUTSySubWhuW6q6grE3freyrh6+gEd9NxCDXaSKQdCvHIyh0/C3mtvhLVUBJ94B/sEN+oiazd5w",
	"hLz7Z1uOvTqyNki1pgv3rJCKlm9cIkzt0pBz13mhNDbZ3ugau88oFx6iK/cGoel7wtm9KdMUjHmanNtB",
	"y2J/I82KlvLAXtvY6a7veNYzF7c2G4JUHfchlhxt2D3FDi8YRThB7mA62PdRWBSTsmBPdO3bmffJ2Txw",
	"FdlcJ3r2nUhaao6LD5Yv3twDUA36osTZ+umqMf37Xx9JXQetJv917csMsfCVlMtMWfluRb14fx1lSkc5",
	"lXTK5bRuOA5eHIVV4YMR2R+eQnTx/prExK7xGk5Hk9HEblYVIGnBSULORpPRGYlJQXHmdjButCZLMgUX",
	"URtP1yOuGUl6tcaJapoDOpnbJeHW0tcS9ILExIeTZFrlpJ1w1CXErVbDIKOlQJJM4gDPwkpR7afy9Ak6",
	"jdJ4n3EQbKvuATrC2mz+9tHzoJQAKklV3cXd6fKnyeRgLXtDkwj07neAkeAGG4RFdSHLSiFc9Tz3boWs",
	"rdwftyZjJ3K6W6Q7NFihs91CnSHw5308606KbSo7BLdJ3FSmRANl5M4myJR5TvUiECfLRDq1NGhq+F0V",
	"k0KZAI3aMxBZtfzXii0OlvDQmFV1C68FZDXA3OnBXGhGiCHG6lJV97SXDarzyS+7JS5bR6FnQ6EPVx+H",
	"PtE1CkMgrOJVXR/D3I5jG8v72/l6Wvu/un/P6v4o2cg26nku/PRiTlSW8RSYSsscJI5MYauSmQFgLkbu",
	"t0vN1dTzwCV1vvf3NuClz3+48sdkBpTVw8Gl9/rkDTeFMtyL92cWikjTmXX21yjjAmzofvtco9mM5sLM",
	"PxOyLfjVf7Pd1CztEb2bnF1M53nD9HALah/MtragvBTIC6pxbAF1wii6VIFMFbNZskjjAlpSH+vj1jfD",
	"eX1zMJztG5u7Ud49azi54Ylin854uGkseCoOXS+5dRFNUyhefKN8NjrUUO7RoY7Nfn1vuTpiVr5OCUAY",
	"kuKNe78iRaj92bNSq6m0Tq7795RhKzgfVk/vCwuM30cae853S6xuOZ8z/XWyeun34dmSfnesTWfDJLev",
	"Dp47yYef60MXH0euXpvneu8c+xcdGV8OzP0tWh/mPqLbqtxW5V5bc6lzuySlFvVtUzIeC5VSMVMGk1eT",
	"VxNi19b6lw32m1zfVf8EAAD///PvfEcJGwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
