version: "3.8"

services:
  auth-service:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: auth-service
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-auth-service:v1.0.0

  server-service:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: server-service
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-server-service:v1.0.0

  monitor-service:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: monitor-service
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-monitor-service:v1.0.0

  heartbeat-gateway:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: heartbeat-gateway
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-heartbeat-gateway:v1.0.0

  ping-worker:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: ping-worker
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-ping-worker:v1.0.0

  mail-worker:
    build:
      context: ..
      dockerfile: deploy/mail-worker.dockerfile
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-mail-worker:v1.0.0

  agent:
    build:
      context: ..
      dockerfile: deploy/microservices.dockerfile
      args:
        SERVICE_NAME: agent
    image: ${DOCKER_REGISTRY:-hariii31}/server-management-agent:v1.0.0
