// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// ReportServerRequest defines model for ReportServerRequest.
type ReportServerRequest struct {
	From      time.Time             `json:"from"`
	Receivers []openapi_types.Email `json:"receivers"`
	To        time.Time             `json:"to"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GenerateServerReportJSONRequestBody defines body for GenerateServerReport for application/json ContentType.
type GenerateServerReportJSONRequestBody = ReportServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GenerateServerReport operation middleware
func (siw *ServerInterfaceWrapper) GenerateServerReport(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:report"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateServerReport(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/servers/report", wrapper.GenerateServerReport)
}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GenerateServerReportRequestObject struct {
	Body *GenerateServerReportJSONRequestBody
}

type GenerateServerReportResponseObject interface {
	VisitGenerateServerReportResponse(w http.ResponseWriter) error
}

type GenerateServerReport202Response struct {
}

func (response GenerateServerReport202Response) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type GenerateServerReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GenerateServerReport400JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GenerateServerReport401JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport403JSONResponse struct{ ForbiddenJSONResponse }

func (response GenerateServerReport403JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response GenerateServerReport500JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(ctx context.Context, request GenerateServerReportRequestObject) (GenerateServerReportResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GenerateServerReport operation middleware
func (sh *strictHandler) GenerateServerReport(ctx *gin.Context) {
	var request GenerateServerReportRequestObject

	var body GenerateServerReportJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateServerReport(ctx, request.(GenerateServerReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateServerReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GenerateServerReportResponseObject); ok {
		if err := validResponse.VisitGenerateServerReportResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVXWvbMBT9K+Zuj27sthsUv6WwjqwMSruxQQlDtW8SFeujV3LBC/rv40p2E9Ns7cPo",
	"U6yPc8+5OkfKFmqjrNGovYNqC4TOGu0wDs5Fc40PHTrPo9pojzp+CmtbWQsvjS7undE85+oNKsFf7wlX",
	"UMG7Yle6SKuu+ERk6HoggRBCDg26mqTlYlAxZ0YDacjhwtCdbBrUb6dgRxlyWGiPpEUbUW+nYaTNHNIj",
	"UoaRPuTwXYvObwzJ39i8nZwJKy8PSC48BVdbsGQskpcpQ7Vp4qzvLUIFzpPUa+5EoXNifXhtCMAv2RxY",
	"Dvk4Y+7usY4xuUZryN/Ew9qL7FTKioyKv4aU8FBBIzweeakQ8kMaapSPSBEqPSo3waISsj2EGyYEkejj",
	"2LyWc2hcElt7m+RG/L6Y5bPu2Q6sO5K+v2FbUrPCykvs553fRP3s4gZFgwQ5aKG4wM+j+dXi6BL7nZSE",
	"Ytl3KAhpxKfRxdjElx/fYAgBo9LqrsrGe5tiJPUqtj+N0/xqka0MZUposZZ6PaZcGS294cPIhOZngE11",
	"XFf6lgt/TRsyNlrWmM2vFpADn0sqfDwrZyWrNxa1sBIqOJ2Vs1PIwQq/iQdTJDJXpPIxJibFhcMS78+i",
	"gQo+o+YhjqmKu5+yeW6a/r9dwEPxDdM8eOowTuy9zyflyfPDTbWydVIvjc4eOuywyVxX1+jcqmvb6PCH",
	"svybrieWYu8vIEKOX4ZMHwsGnb4Mmjy6H1+jbPoy798CqG63k/zeQvK8GixfhmUOrlNKUL9n9BhDGq32",
	"Yu0YnYyBZfg3Syqb0hVXO2qH21AVRWtq0W6M89VZeVYC7x3qb8cLOfCE/GnmQrYIYRn+BAAA//97Lhhu",
	"pwcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
