// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// LiveStatusItem defines model for LiveStatusItem.
type LiveStatusItem struct {
	Ipv4       *string `json:"ipv4,omitempty"`
	ServerId   *string `json:"server_id,omitempty"`
	ServerName *string `json:"server_name,omitempty"`
	Status     *string `json:"status,omitempty"`
}

// LiveStatusListResponse defines model for LiveStatusListResponse.
type LiveStatusListResponse struct {
	Items        *[]LiveStatusItem `json:"items,omitempty"`
	Total        *int              `json:"total,omitempty"`
	TotalOffline *int              `json:"total_offline,omitempty"`
	TotalOnline  *int              `json:"total_online,omitempty"`
	TotalUnknown *int              `json:"total_unknown,omitempty"`
}

// ReportServerRequest defines model for ReportServerRequest.
type ReportServerRequest struct {
	From      time.Time             `json:"from"`
	Receivers []openapi_types.Email `json:"receivers"`
	To        time.Time             `json:"to"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetMonitorLivestatusParams defines parameters for GetMonitorLivestatus.
type GetMonitorLivestatusParams struct {
	From int `form:"from" json:"from"`
	To   int `form:"to" json:"to"`
}

// GenerateServerReportJSONRequestBody defines body for GenerateServerReport for application/json ContentType.
type GenerateServerReportJSONRequestBody = ReportServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get paginated live status of servers
	// (GET /monitor/livestatus)
	GetMonitorLivestatus(c *gin.Context, params GetMonitorLivestatusParams)
	// Generate server report
	// (POST /monitor/report)
	GenerateServerReport(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMonitorLivestatus operation middleware
func (siw *ServerInterfaceWrapper) GetMonitorLivestatus(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"monitor:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonitorLivestatusParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMonitorLivestatus(c, params)
}

// GenerateServerReport operation middleware
func (siw *ServerInterfaceWrapper) GenerateServerReport(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"monitor:report"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateServerReport(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/monitor/livestatus", wrapper.GetMonitorLivestatus)
	router.POST(options.BaseURL+"/monitor/report", wrapper.GenerateServerReport)
}

type BadRequestJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GetMonitorLivestatusRequestObject struct {
	Params GetMonitorLivestatusParams
}

type GetMonitorLivestatusResponseObject interface {
	VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error
}

type GetMonitorLivestatus200JSONResponse LiveStatusListResponse

func (response GetMonitorLivestatus200JSONResponse) VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitorLivestatus400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMonitorLivestatus400JSONResponse) VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitorLivestatus401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMonitorLivestatus401JSONResponse) VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitorLivestatus403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetMonitorLivestatus403JSONResponse) VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitorLivestatus500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMonitorLivestatus500JSONResponse) VisitGetMonitorLivestatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReportRequestObject struct {
	Body *GenerateServerReportJSONRequestBody
}

type GenerateServerReportResponseObject interface {
	VisitGenerateServerReportResponse(w http.ResponseWriter) error
}

type GenerateServerReport202Response struct {
}

func (response GenerateServerReport202Response) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type GenerateServerReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GenerateServerReport400JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GenerateServerReport401JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport403JSONResponse struct{ ForbiddenJSONResponse }

func (response GenerateServerReport403JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response GenerateServerReport500JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get paginated live status of servers
	// (GET /monitor/livestatus)
	GetMonitorLivestatus(ctx context.Context, request GetMonitorLivestatusRequestObject) (GetMonitorLivestatusResponseObject, error)
	// Generate server report
	// (POST /monitor/report)
	GenerateServerReport(ctx context.Context, request GenerateServerReportRequestObject) (GenerateServerReportResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetMonitorLivestatus operation middleware
func (sh *strictHandler) GetMonitorLivestatus(ctx *gin.Context, params GetMonitorLivestatusParams) {
	var request GetMonitorLivestatusRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitorLivestatus(ctx, request.(GetMonitorLivestatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitorLivestatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMonitorLivestatusResponseObject); ok {
		if err := validResponse.VisitGetMonitorLivestatusResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateServerReport operation middleware
func (sh *strictHandler) GenerateServerReport(ctx *gin.Context) {
	var request GenerateServerReportRequestObject

	var body GenerateServerReportJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateServerReport(ctx, request.(GenerateServerReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateServerReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GenerateServerReportResponseObject); ok {
		if err := validResponse.VisitGenerateServerReportResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWUWvkNhD+K2baRyfeXK5w+C0HTdkmpSFpaSEsh2KPvbpakjOSt7jB/72MJK/XXV9y",
	"hZCXe1tZmvk+zXzzaZ+gMKo1GrWzkD8BoW2NtugXH0V5i48dWserwmiH2v8UbdvIQjhpdPbZGs3fbLFF",
	"JfjX94QV5PBdNqXOwq7NfiQydBtBYBiGFEq0BcmWk0HOmAlF0CGFS0MPsixRvx2DCXJIYa0dkhaNj3o7",
	"DiNsYpF2SAl6+CGF37Xo3NaQ/AfLt6MzQ+XtGMmJ58H5E7RkWiQng4YKU/qvrm8RcrCOpK75JgqtFfXy",
	"XhTAJ1kubA/p+MU8fMbCy+Ra7vDOCdfZtUN1zEK2u/eLSKG+y0D7XS3UMk/rIf83x2tp3ZcrJh2q+Y/n",
	"evefm0/Agkj0fm2caA44Su2wRtpvfTJV1UiNzx7RL53o9F/a/K2XjiwV4xZbQ+7O1/fAY+aVqMj4XlaG",
	"lHCQQykcnjipENIl0RQod0jz2u1jUQnZLMUd1+trMaNSJfEs3ge6Pv6QzObo9l5YRUfS9XfcxXBZ0cor",
	"7C86t/X8eey2KEokSCEIEP48ubhZn1xhP1EJUUz7AQUhjfFhdTle4uc/foM4tRwVdqcsW+faMPdSV/76",
	"8/m/uFknlaFECS1qqevRlpTR0hkuRiI0+zY31XJe6RpO/Es4kHCjZYHJxc0aUuC6hMRnp6vTFbM3LWrR",
	"Ssjh/HR1eg4ptMJtfWGyiJI1cofTxNXoFcN68Z63LiGHn9BFyOvpMOciodB5bdzH4j52SP1U29i8qZ+O",
	"OkwPDFRJLVWnIF+lCwpfThql8GLKs4WUm3T+GL9brV7N8L9gRQvO/+sVd+d9wF5KueeYHfxb8CFnL4fM",
	"3xUOOn85aPY+//A1zOaP+OH8eTkcTs49RLXlhKKEDbfBdkoJ6oO8kpYnQDgsE9ZjEjSWmCrOhFe/qFlo",
	"EOwNNoy4V3EYEm92xi5KWPMSR2/0p/dP4kdT9q8mgyUTHuauxpIdjpT47tgiQq6kDuyl0cljhx2Wie2K",
	"Aq2tuqbpv10t+S4eqSl0enRTGnt9rJ9nYULaqD7e7aiJpp5nWWMK0WyNdfmH1YcV8NmY/2m0qYjDLha/",
	"XMoGYdgM/wYAAP//ubpdyh8MAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
